### ISSUE TITLE
Динамичные title у страниц

### ISSUE THREAD

**Issue by h0x000** [JIoJIaJIu/goldpoisk_frontend#257]
Нужно сделать динамичные title у каждой страницы, например у этой страницы http://goldpoisk.ru/item/zolotoe-koltso-s-granatami-i-fianitami-22 есть заголовок h1 с таким названием "Золотое Кольцо с гранатами и фианитами", в нашем случае заголовок у продуктов, которые идут на продажу, должен быть таким "Купить Золотое Кольцо с гранатами и фианитами".

**Comment by YLeight** [comment]
Moved to redmine
