### ISSUE TITLE
[Таск] Тестовая задача

### ISSUE THREAD

**Issue by JIoJIaJIu** [JIoJIaJIu/goldpoisk_frontend#278]
Дабы освоить принцип этого таскменеджмента
* В момент выполнения ставится лейбл "В процессе"
* В конце выполнения ставится "Решена"

Для оформления используется [маркдаун](https://guides.github.com/features/mastering-markdown/)
чтобы указать кого-либо в комментарии или задаче нужно начать писать [at] @ 
Пример: @AlexandrTokmakov

**Comment by YLeight** [comment]
Fired
