### ISSUE TITLE
[Таск] посмотреть проект

### ISSUE THREAD

**Issue by JIoJIaJIu** [JIoJIaJIu/goldpoisk_frontend#292]
Нужно составить полное впечатление о проекте и, по возможности, запомнить сленг

* Главную
  Карусель, где картинки называется `g-promotion` (g- префикс в нотации БЭМа, типа Goldpoisk)
  Лучшие предложения `g-bids`, у них есть отдельная страница goldpoisk.ru/bids
* Каждый каталог, всю пагинацию, фильтрацию, сортировку. Товар в каталоге - `g-product`
* Страницу товара, итем - `g-item`

Я думаю начать документировать такие моменты, что думаешь?

**Comment by YLeight** [comment]
Fired
