### ISSUE TITLE
[Обсуждение] Баннеры

### ISSUE THREAD

**Issue by JIoJIaJIu** [JIoJIaJIu/goldpoisk_frontend#320]
Загружал разные картинки и очень понравилась гамма этого фото, так мими смотрится, в данном стиле. 
Что думаешь? Может сделать что-то похожее? В дополнение
![g-promotion](https://cloud.githubusercontent.com/assets/601863/7472351/c2040e1e-f35b-11e4-991c-bf0afafcec01.png)

Кстати таким образом мы можем оформлять не тоьлко баннеры, но и новости, к примеру)
Какие-нибудь важные элементы из жизни голдпоиска, мол в нашем каталоге 30к товаров! и красивая девочка. 
Хотя ты так и задумывала, наверное? Я что-то не предусмотрел текст кастомный(
@YLeight @AlexandrTokmakov

**Comment by YLeight** [comment]
About nothing
