### ISSUE TITLE
[Обсуждение] Пользовательские метки

### ISSUE THREAD

**Issue by JIoJIaJIu** [JIoJIaJIu/goldpoisk_frontend#335]
Интересное решение на сайте санлайта http://www.love-sl.ru/catalog/ring135876.html
![mark](https://cloud.githubusercontent.com/assets/601863/7494158/4e371b5e-f430-11e4-8df0-75dfb105dea3.png)

@YLeight @AlexandrTokmakov

**Comment by YLeight** [comment]
Frozen
