### ISSUE TITLE
[Таск] Рефакторинг Gold585

### ISSUE THREAD

**Issue by JIoJIaJIu** [JIoJIaJIu/goldpoisk_frontend#341]
Нужно отрефакторить Gold585.java
родительский таск https://github.com/JIoJIaJIu/goldpoisk_frontend/issues/317

Пример [Sunlight.java](https://github.com/JIoJIaJIu/goldpoisk_parser/blob/master/src/main/java/com.goldpoisk.app/stores/Sunlight.java)
[Конфигурация](https://github.com/JIoJIaJIu/goldpoisk_parser/blob/master/stores.ini)

Все логги(формат) должны быть идентичны

**Comment by YLeight** [comment]
Moved to redmine
