### ISSUE TITLE
Заполнить title и description для всех страниц из навигации

### ISSUE THREAD

**Issue by h0x000** [JIoJIaJIu/goldpoisk_frontend#353]
Я составил таблицу: https://drive.google.com/open?id=1ohYc64Ftwj4KbV-7sxF5-BTR1PV7SZ6naMSaBl_d0VQ&authuser=0 где напротив каждой страницы указаны необходимые title и description, а внизу пример кода.

**Comment by YLeight** [comment]
Moved to redmine
