### ISSUE TITLE
[Таск] Галлерея фотографий

### ISSUE THREAD

**Issue by JIoJIaJIu** [JIoJIaJIu/goldpoisk_frontend#360]
При щелчке по лупе открывается галлерея
Хочется:
* Иметь возможность проскроливать фотки
* Чтобы была показана кнопка купить и сумма (на полупрозрачном фоне)
* Был заголовок, который бы позволял пройти на страницу товара
* Скролить можно все фотки, переключаясь на следующий/предыдущий товар

**Comment by YLeight** [comment]
Frozen
