### ISSUE TITLE
url итема должен содержать название раздела

### ISSUE THREAD

**Issue by h0x000** [JIoJIaJIu/goldpoisk_frontend#390]
Пример:
сейчас так - http://goldpoisk.ru/item/braslet-s-brilliantami-4
должно быть вот так - http://goldpoisk.ru/brasleti/braslet-s-brilliantami-4

Благодаря этому робот поймет к какому разделу принадлежит данный итем. В нашем случае по url понятно, что итем принадлежит к браслетам.

Для генерации правильного транслит-названия юзай: http://translit.net
Пиши например: НАЗВАНИЕ и жми В ТРАНСЛИТ и получишь NAZVANIE

После, нужно чтобы по старому пути эти итемы небыли доступны. Обнови sitemap и можно оффать задачку.

**Comment by YLeight** [comment]
Moved to redmine backlog
