### ISSUE TITLE
description у товаров слишком длинный

### ISSUE THREAD

**Issue by h0x000** [JIoJIaJIu/goldpoisk_frontend#395]
Я переборщил с длинной description для товаров, нужно чтобы выглядело так:

У нас можно не только купить золотое кольцо с бриллиантами, но и подобрать для себя что-то более редкое по доступной цене!

золотое кольцо с бриллиантами - это название товара, берем его из h1 и переводим в нижний регистр

Примеры:

1. У нас можно не только купить золотое кольцо с бриллиантами, но и подобрать для себя что-то более редкое по доступной цене!

2. У нас можно не только купить браслет с бриллиантами, но и подобрать для себя что-то более редкое по доступной цене!

3. У нас можно не только купить золотое колье с бриллиантом, но и подобрать для себя что-то более редкое по доступной цене!

4. -

5. У нас можно не только купить подвес золотой с бриллиантами, но и подобрать для себя что-то более редкое по доступной цене!

6. У нас можно не только купить серебряные серьги с фианитом, но и подобрать для себя что-то более редкое по доступной цене!

7. -

8. У нас можно не только купить золотые часы ника лилия 0425.0.1.51, но и подобрать для себя что-то более редкое по доступной цене!

9. -

**Comment by YLeight** [comment]
Moved to redmine backlog
