### ISSUE TITLE
404 ошибки со страницы просмотра товара

### ISSUE THREAD

**Issue by h0x000** [JIoJIaJIu/goldpoisk_frontend#396]
Заходим сюда: http://goldpoisk.ru/item/zolotoe-kole-s-brilliantom и тыкаем на любую категорию правой клавишей "Открыть ссылку в новой вкладке" и наблюдаем 404 ответ. Робот жалуется на все 9 категорий.

**Comment by YLeight** [comment]
Moved to redmine backlog
