### ISSUE TITLE
[Таск] Социальные иконки

### ISSUE THREAD

**Issue by JIoJIaJIu** [JIoJIaJIu/goldpoisk_frontend#411]
> Связана с #381 
Блок yashare (https://tech.yandex.ru/share/) вяжется к странице, возникает проблема при COMET обновлении страницы.
Необходимо ответить на вопрос
Как привязать блок yashare не к странице, а к конкретному блоку на ней, и по какому критерию вести счётчик на yashare.

https://github.com/JIoJIaJIu/goldpoisk_frontend/issues/401#issuecomment-122640954

**Comment by YLeight** [comment]
Moved to redmine
